language: python

python:
  - 2.6
  - 2.7

before_install:
  - sudo apt-get install libevent-dev
  - pip install --use-mirrors gevent nose fakeredis==0.3.0 testtools

install:
  - python setup.py install

script: nosetests --exe -w tests
